//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    /// <summary>
    /// Defines the <see cref="BootStrapCreateWorkoutPlan" />.
    /// </summary>
    public partial class BootStrapCreateWorkoutPlan
    {
        /// <summary>
        /// form control..
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form;

        /// <summary>
        /// GenderLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label GenderLabel;

        /// <summary>
        /// Gender control..
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList Gender;

        /// <summary>
        /// AgeLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label AgeLabel;

        /// <summary>
        /// Age control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Age;

        /// <summary>
        /// HeightLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label HeightLabel;

        /// <summary>
        /// Height control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Height;

        /// <summary>
        /// WeightLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label WeightLabel;

        /// <summary>
        /// Weight control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Weight;

        /// <summary>
        /// CalorieIntakeLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label CalorieIntakeLabel;

        /// <summary>
        /// CalorieIntake control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox CalorieIntake;

        /// <summary>
        /// GoalsLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label GoalsLabel;

        /// <summary>
        /// Goals control..
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList Goals;

        /// <summary>
        /// EmailSecurityLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label EmailSecurityLabel;

        /// <summary>
        /// Email control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Email;

        /// <summary>
        /// Label1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// Logo control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Image Logo;
    }
}
