//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    /// <summary>
    /// Defines the <see cref="BootStrapViewDataByAge" />.
    /// </summary>
    public partial class BootStrapViewDataByAge
    {
        /// <summary>
        /// form control..
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form;

        /// <summary>
        /// DropDownList1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;

        /// <summary>
        /// Chart1 control..
        /// </summary>
        protected global::System.Web.UI.DataVisualization.Charting.Chart Chart1;
    }
}
