//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    /// <summary>
    /// Defines the <see cref="BootStrapLoginPage" />.
    /// </summary>
    public partial class BootStrapLoginPage
    {
        /// <summary>
        /// form control..
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form;

        /// <summary>
        /// UsernameLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UsernameLabel;

        /// <summary>
        /// UsernameTextBox control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;

        /// <summary>
        /// PasswordLabel control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label PasswordLabel;

        /// <summary>
        /// PasswordTextBox control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;

        /// <summary>
        /// LoginLabel1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LoginLabel1;
    }
}
