//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    /// <summary>
    /// Defines the <see cref="CreateWorkoutPlan" />.
    /// </summary>
    public partial class CreateWorkoutPlan
    {
        /// <summary>
        /// form1 control..
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Menu1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Menu Menu1;

        /// <summary>
        /// Gender control..
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList Gender;

        /// <summary>
        /// Age control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Age;

        /// <summary>
        /// Height control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Height;

        /// <summary>
        /// Weight control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Weight;

        /// <summary>
        /// CalorieIntake control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox CalorieIntake;

        /// <summary>
        /// Goals control..
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList Goals;

        /// <summary>
        /// Email control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Email;

        /// <summary>
        /// Button1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button1;

        /// <summary>
        /// Label1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// Image1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Image Image1;
    }
}
