//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    /// <summary>
    /// Defines the <see cref="WebForm2" />.
    /// </summary>
    public partial class WebForm2
    {
        /// <summary>
        /// form1 control..
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LinkButton1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton1;

        /// <summary>
        /// Email control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Email;

        /// <summary>
        /// Username control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Username;

        /// <summary>
        /// Password control..
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox Password;

        /// <summary>
        /// LoginButton control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Button LoginButton;

        /// <summary>
        /// Label1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// Image1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.Image Image1;
    }
}
