//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    /// <summary>
    /// Defines the <see cref="GainWeight" />.
    /// </summary>
    public partial class GainWeight
    {
        /// <summary>
        /// form1 control..
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// GridView1 control..
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView1;
    }
}
